# ~/.tmuxinator/sample.yml

name: sample
root: /sample

windows:
  - react:
      layout: main-horizontal
      panes:
        - n lts
        -
        -
  - server:
      layout: main-vertical
      panes:
        -
        -
