#!/bin/bash

alias ls='ls -larth'
alias grep='grep --color -rin'
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias chrome-unsafe="open /Applications/Google\ Chrome.app --args --disable-web-security"
