#!/bin/bash

# JAVA
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home

# android SDK
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

# system PATH
export PATH=$PATH:/bin
export PATH=$PATH:/sbin

# user PATH
# export PATH=$PATH:/usr/local/Cellar
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/local/Cellar/python/2.7.14/bin
export PATH=$PATH:/usr/bin
export PATH=$PATH:/usr/sbin

# home PATH
export PATH=$HOME:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/dotfiles/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.fastlane/bin:$PATH
export PATH=$HOME/.yarn/bin:$PATH
export PATH=$HOME/.rvm/bin:$PATH
export PATH=$HOME/Library/PostgreSQL/9.5/bin:$PATH
